### ISSUE TITLE
client installation in c++

### ISSUE THREAD

**Issue by sidis8066** [NVIDIA/tensorrt-inference-server#498] opened 2019-07-25 15:23 UTC
Hi guys,Is anyone working on tensorrt for c++ on ubuntu 16.04.Can please help regarding installation for client.

**Comment by GuanLuo** [comment] 2019-07-25 16:55
Are you referring to the example clients for TensorRT Inference Server? If so, the documentation has included the build step [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/build.html#building-the-client-libraries-and-examples).

**Comment by sidis8066** [comment] 2019-07-25 17:08
I followed all the installations Docker.client i dont know what to do next..

**Comment by CoderHam** [comment] 2019-07-25 17:21
You can refer to the documentation for the TRTIS client API [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/client.html#image-classification-example-application).
Also the sample client code should also be useful: [simple_client.cc](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/simple_client.cc)

**Comment by sidis8066** [comment] 2019-07-25 18:29
i tried by installing Docker.client files and moved it src to /usr/include and then update protobuf and run simple c++ code as attached i am getting errors.If anyone know the entire flow please help me to done.I am beginner to c++ i run this code in  python its working but i want to run on c++.
[tensort_error.log](https://github.com/NVIDIA/tensorrt-inference-server/files/3432796/tensort_error.log)

**Comment by CoderHam** [comment] 2019-07-25 18:34
This is caused by different versions of protobuf. Check that the version you are installing (or have installed) is the same as that being used by the client library. 
It runs on python probably because you are using an Anaconda distribution that might ship with the appropriate protobuf version.

**Comment by sidis8066** [comment] 2019-07-25 20:23
How can i get the protobuf version used in client what is tbe protobuf version used in client

**Comment by sidis8066** [comment] 2019-07-26 11:24
i just run Docker.client what to do next can anyone guides me.

**Comment by GuanLuo** [comment] 2019-07-29 16:38
Once the Docker.client container is built, you can continue your development inside the container as the dependencies are configured and installed for you, so you don't have to worry about the protobuf version issue.

If you want to develop outside docker container, you can either:

1. re-generate the C++ `.proto` files so that the generated `pb.h` and `pb.cc` files are targeted on the protobuf version on your system (see [detail](https://developers.google.com/protocol-buffers/docs/cpptutorial#compiling-your-protocol-buffers))
2. Install the dependencies (see `Dockerfile.client`) and run the cmake and make [command](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile.client#L79) directly, which build all the client related files and also conduct 1. for you.
3. Install protobuf 3.6.1, which is the version used in the client container

**Comment by deadeyegoodwin** [comment] 2019-07-29 22:16
@sidis8066 Did you follow the quickstart guide? https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/quickstart.html

It walks through the entire process of running the server and a client. If it is not clear we'd like to know what step didn't work for you.

**Comment by deadeyegoodwin** [comment] 2019-08-02 21:12
Closing. Let us know if you have problems following the quickstart guide.

**Closed by deadeyegoodwin** 2019-08-02 21:12 UTC
