### ISSUE TITLE
NMT output different from normal inference

### ISSUE THREAD

**Issue by damitkwr** [NVIDIA/tensorrt-inference-server#381] opened 2019-06-17 15:15 UTC
Hi all,

I am using NVIDIA' s implementation of [GNMTv2](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Translation/GNMT) and TRTIS v19.05. I have trained a model in a saved model format which works fine with Tensorflow Serving but is having unexpected outputs when the same saved model is served through the TRTIS. Note that I have changed the output from the transpose node which has a tensor shape of (5, -1, -1) to the index_to_string_Lookup node which has a shape of (-1, -1, 5) to allow for TRTIS to work since TRTIS needs the first dimension to be a variable dimension. 

In short, the problem is that I am getting a tensor of (1, 1, 5) back from TRTIS instead of the (1, 4, 5) back I would get if I were running TF-Serving or just normally running the model in a notebook.

Expected output (This is the output from TF-Serving): 

> {
>     "predictions": [[["regular", "regular", "regular", "regulator", "regul@@"]], [["eye@@", "sunglasses", "eye", "eye@@", "are"]], [["glasses", "</s>", "glasses", "glasses", "sunglasses"]], [["</s>", "</s>", "</s>", "</s>", "</s>"]]
>     ]
> }

Actual output (Output from TRTIS):

>  * Connected to localhost (::1) port 8000 (#0)
>  POST /api/infer/sp_corrector/1?format=binary HTTP/1.1
> Host: localhost:8000
> User-Agent: libcurl-agent/1.0
> Accept: */*
> Content-Type: application/octet-stream
> NV-InferRequest:batch_size: 1 input { name: "source" dims: 4 } input { name: "source_sequence_length" dims: 1 } output { name: "predictions" }
> Content-Length: 20
>  We are completely uploaded and fine
> < HTTP/1.1 200 OK
> < NV-InferResponse: model_name: "sp_corrector" model_version: 1 batch_size: 1 output { name: "predictions" raw { dims: 1 dims: 5 batch_byte_size: 57 } }
> < NV-Status: code: SUCCESS server_id: "inference:0" request_id: 8
> < Content-Type: application/octet-stream
> < Content-Length: 98
> <
> * Connection #0 to host localhost left intact
> [['regular' 'regular' 'regular' 'regulator' 'regul@@']]

As you can see, we are only getting the first word output from the model. Here is the configuration for the TRTIS:

> name: "sp_corrector"
> platform: "tensorflow_savedmodel"
> max_batch_size: 32
> input [
>   {
>     name: "source"
>     data_type: TYPE_INT32
>     dims: [ -1 ]
>   },
>   {
>     name: "source_sequence_length"
>     data_type: TYPE_INT32
>     dims: [ 1 ]
>         reshape: {shape: [ ]}
>   }
> ]
> output [
>   {
>     name: "predictions"
>     data_type: TYPE_STRING
>     dims: [ -1, 5 ]
>   }
> ]

This is the output from the saved_model_cli when I did show on the saved_model:

> MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:
> 
> signature_def['serving_default']:
>   The given SavedModel SignatureDef contains the following input(s):
>     inputs['source'] tensor_info:
>         dtype: DT_INT32
>         shape: (-1, -1)
>         name: source:0
>     inputs['source_sequence_length'] tensor_info:
>         dtype: DT_INT32
>         shape: (-1)
>         name: source_sequence_length:0
>   The given SavedModel SignatureDef contains the following output(s):
>     outputs['predictions'] tensor_info:
>         dtype: DT_STRING
>         shape: (-1, -1, 5)
>         name: tower_0/v0/index_to_string_Lookup:0
>   Method name is: tensorflow/serving/predict

Let me know if somebody needs the saved_model file to reproduce this problem or to dive in further, thanks!

**Comment by damitkwr** [comment] 2019-06-17 19:01
Update:

I tried reshaping the output to a flattened tensor and I am still having the issue:

Output from tf-serving:

> {
>     "predictions": ["regular", "eye@@", "glasses", "</s>" ]
> }

Output from TRTIS:

> < HTTP/1.1 200 OK
> < Content-Type: application/octet-stream
> < NV-Status: code: SUCCESS server_id: "inference:0" request_id: 3
> < Content-Length: 231
> <
> * Connection #0 to host localhost left intact
> id: "inference:0"
> version: "1.2.0"
> uptime_ns: 636411144121
> model_status {
>   key: "spelling_model"
>   value {
>     config {
>       name: "spelling_model"
>       platform: "tensorflow_savedmodel"
>       version_policy {
>         latest {
>           num_versions: 1
>         }
>       }
>       max_batch_size: 32
>       input {
>         name: "source"
>         data_type: TYPE_INT32
>         dims: -1
>       }
>       input {
>         name: "source_sequence_length"
>         data_type: TYPE_INT32
>         dims: 1
>         reshape {
>         }
>       }
>       output {
>         name: "predictions"
>         data_type: TYPE_STRING
>         dims: 1
>         reshape {
>         }
>       }
>       instance_group {
>         name: "spelling_model"
>         count: 1
>         gpus: 0
>         kind: KIND_GPU
>       }
>       default_model_filename: "model.savedmodel"
>     }
>     version_status {
>       key: 1
>       value {
>         ready_state: MODEL_READY
>       }
>     }
>   }
> }
> ready_state: SERVER_READY
> 
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 8000 (#0)
> > POST /api/infer/spelling_model/1?format=binary HTTP/1.1
> Host: localhost:8000
> User-Agent: libcurl-agent/1.0
> Accept: */*
> Content-Type: application/octet-stream
> NV-InferRequest:batch_size: 1 input { name: "source" dims: 4 } input { name: "source_sequence_length" dims: 1 } output { name: "predictions" }
> Content-Length: 20
> 
> * We are completely uploaded and fine
> < HTTP/1.1 200 OK
> < NV-InferResponse: model_name: "spelling_model" model_version: 1 batch_size: 1 output { name: "predictions" raw { dims: 1 batch_byte_size: 11 } }
> < NV-Status: code: SUCCESS server_id: "inference:0" request_id: 4
> < Content-Type: application/octet-stream
> < Content-Length: 53
> <
> * Connection #0 to host localhost left intact
> ['regular']

The problem is in the beam searching decoding layer. It seems to only do one iteration of the loop and not for the rest of the words.

**Comment by deadeyegoodwin** [comment] 2019-06-17 23:41
Can you share the model and the client script you are running that shows the failure so we can try to repro.

**Comment by damitkwr** [comment] 2019-06-18 00:34
> Can you share the model and the client script you are running that shows the failure so we can try to repro.

I will send the link to your NVIDIA email, let me know if anybody else wants the model file as the GNMTv2 model file is large

**Comment by deadeyegoodwin** [comment] 2019-06-21 21:02
Thanks for providing the repro. We will take a look.

**Comment by CoderHam** [comment] 2019-06-26 19:59
I was able to reproduce the bug. Currently investigating what is going wrong with the beam search layer.

**Comment by CoderHam** [comment] 2019-06-29 01:33
@damitkwr, when you set the `max_batch_size` to a non-zero value, TRTIS assumes the _first_ dimension of the model output is the batch dimension but in the case of the model you have provided, it appears that the _second_ dims is the `batch_size`.  

The shape you expect for the model is (**1**,4,5) however the Output from the TF model is (4,**1**,5). 

This may be caused by the following step you said you do:

> Note that I have changed the output from the transpose node which has a tensor shape of (5, -1, -1) to the index_to_string_Lookup node which has a shape of (-1, -1, 5) to allow for TRTIS to work since TRTIS needs the first dimension to be a variable dimension.

Once you fix it to have the first dimension as the batch dimension, it should work fine. Closing this issue for now, if the issue persists you can re-open this issue.

**Closed by CoderHam** 2019-06-29 01:33 UTC
