### ISSUE TITLE
Building the Server Failed

### ISSUE THREAD

**Issue by pwlazy** [NVIDIA/tensorrt-inference-server#169] opened 2019-03-20 10:52 UTC
sudo docker build --pull -t tensorrtserver_build --target trtserver_build .

then the error is as below

`Analyzing: 25 targets (182 packages loaded, 10303 targets configured)
Analyzing: 25 targets (182 packages loaded, 10303 targets configured)
ERROR: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/workspace.bzl:896:5: no such package '@grpc//': java.io.IOException: thread interrupted and referenced by '//external:grpc_python_plugin'
ERROR: Analysis of target '//src/clients/python:build_pip' failed; build aborted: Analysis failed
INFO: Elapsed time: 168.496s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (182 packages loaded, 10303 targets configured)
FAILED: Build did NOT complete successfully (182 packages loaded, 10303 targets configured)`

some env information is as below

> Docker version 18.09.0, build 4d60db4
tensorrtserver 19.02-py3
cuda 10
cudnn 7.3
cuda Driver Version: 410.48
bazel version : Build label: 0.20.0- (@non-git)

**Comment by erickim555** [comment] 2019-03-20 21:41
Which git commit are you using? For what it's worth, I'm on 306b268189c42ef6d709aac5b55eb3a039a05d3c, and building the server seems to work for me. You could try the recent release tag https://github.com/NVIDIA/tensorrt-inference-server/releases/tag/v1.0.0 , this is a stable release.

**Comment by pwlazy** [comment] 2019-03-21 01:49
i used the git branch "r19.02"

**Comment by deadeyegoodwin** [comment] 2019-03-21 15:51
I am unable to reproduce the failure using r19.02. Did you try the build more than once? Also, make sure you have plenty of disk space available before starting the build. It seems that bazel is unable to find one of the build dependencies... but it should have downloaded and installed that itself.

**Comment by pwlazy** [comment] 2019-03-22 09:10
i use the git branch "v1.0.0" to build the server, it works!

```
Removing intermediate container dd3e2c23d858
 ---> a89ce54009ac
Successfully built a89ce54009ac
Successfully tagged tensorrtserver_build:latest
```

then, i run the built image
```
sudo nvidia-docker run  --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/weipeng.pengw/work/model_repository:/models tensorrtserver_build trtserver  --model-store=/models
```
then a error is as below
```
===============================
== TensorRT Inference Server ==
===============================

NVIDIA Release 19.03 (build 5809531)
.............
.............
/opt/tensorrtserver/nvidia_entrypoint.sh: line 88: exec: trtserver: not found
```

**Comment by deadeyegoodwin** [comment] 2019-03-22 16:57
Looks like you are following the development build instructions from here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#incremental-builds

The "build" container you have built doesn't have PATH and LD_LIBRARY_PATH setup to run the server. But it is easy enough to add them yourself. Or you can just run like this:

**Comment by deadeyegoodwin** [comment] 2019-03-22 17:00
BTW, if you are trying to build the "final" version of the container (not the development version) you should follow the instructions in this section: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#building-the-server

That container will have PATH and LD_LIBRARY_PATH already set for you.

**Comment by deadeyegoodwin** [comment] 2019-03-25 15:55
Closing. Please reopen if additional problems.

**Closed by deadeyegoodwin** 2019-03-25 15:55 UTC

**Comment by globalmaster** [comment] 2020-06-08 08:21
I run: docker pull nvcr.io/nvidia/tritonserver:20.03.1-py3
then run: nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/hezhiming/triton-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.03.1-py3 --model-repository=/models
I got this error: /opt/tritonserver/nvidia_entrypoint.sh: line 93: exec: --: invalid option

How can I solve this error? @erickim555 @deadeyegoodwin @sublee @dougn

**Comment by deadeyegoodwin** [comment] 2020-06-08 15:55
You need to specify an executable when you use docker:

nvcr.io/nvidia/tritonserver:20.03.1-py3 **tritonserver** --model-repository=/models

**Comment by elve960520** [comment] 2020-08-25 03:08
> You need to specify an executable when you use docker:
> 
> nvcr.io/nvidia/tritonserver:20.03.1-py3 **tritonserver** --model-repository=/models

but i do that it shows

` =============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.03 (build 11042949)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for the inference server.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

/opt/tensorrtserver/nvidia_entrypoint.sh: line 92: exec: tritonserver: not found
`

**Comment by nikhil-salodkar** [comment] 2020-10-28 14:23
> /opt/tensorrtserver/nvidia_entrypoint.sh: line 92: exec: tritonserver: not found
> `

I am also facing the exact same error when trying to follow the triton inference server documentation. Can anyone help in understanding whey this could be happening?

**Comment by levinxo** [comment] 2020-11-23 13:31
@nikhil-salodkar You could try `trtserver` instead of `tritonserver `
