### ISSUE TITLE
Op type not registered 'BatchMatMulV2' in binary running 

### ISSUE THREAD

**Issue by superhg2012** [NVIDIA/tensorrt-inference-server#855] opened 2019-11-12 07:02 UTC
**Description**

when try to run my tensorflow savedmoel on TRTIS . it failed to start up with below error:

> failed to load 'trt_model' version 1: Not found: Op type not registered 'BatchMatMulV2' in binary running on fa60ca095bbf. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**TRTIS Information**
I am using TRTIS 1.5.0  

container  19.06
CUDA Version 10.1.24
Driver Version: 418.87.01

OS : ubuntu 16.04

**To Reproduce**

**Expected behavior**
The is the output of runing cmd line "curl localhost:8000/api/status"
id: "inference:0"
version: "1.3.0"
uptime_ns: 235795201147
model_status {
  key: "trt_model"
  value {
    config {
      name: "trt_model"
      platform: "tensorflow_savedmodel"
      version_policy {
        all {
        }
      }
      input {
        name: "input"
        data_type: TYPE_INT32
        dims: -1
      }
      input {
        name: "input_lengths"
        data_type: TYPE_INT32
        dims: -1
      }
      input {
        name: "split_infos"
        data_type: TYPE_INT32
        dims: -1
      }
      output {
        name: "out0"
        data_type: TYPE_FP32
        dims: -1
      }
      instance_group {
        name: "trt_model"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_UNAVAILABLE
      }
    }
  }
}

If  the model deployment is ok , the reday_status will be "MODEL_READY", so   how to solve this problem?

**Comment by GuanLuo** [comment] 2019-11-12 17:10
After looking through TF's Github commit history,  I don't think we can test this kind of mismatch. The cause seems to be that the op ('BatchMatMulV2') is added after TF 1.13, while TRTIS 19.06 container uses TF 1.13 and thus the op can't be found there.

Can you try to use a newer TRTIS container to see if it resolves the issue? Our [release page](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-10.html#rel_19-10) shows what framework versions that the release built with, and it shows that container since 19.07 is using TF 1.14.

**Comment by superhg2012** [comment] 2019-11-13 02:12
@GuanLuo My model was trained with tensorflow 1.11 version and deployment env tf version is 1.13.  if deployed with tf serving, it's ok.   container 19.07 starts to use ubuntu 18.04 os which is unavialible for me now.

**Comment by GuanLuo** [comment] 2019-11-13 02:32
I see, then my assertion is probably wrong. That might be that the TF contri ops are not built in TRTIS 19.06 (fixed by #421). Here is a similar [issue](https://github.com/NVIDIA/DeepLearningExamples/issues/280) and it is resolved by using a newer TRTIS container.

For your case, since Ubuntu 18.04 is not available for you, to check if #421 fixes this, I am afraid you will need to build 19.06 release from source, but with #421 applied.

**Comment by deadeyegoodwin** [comment] 2019-11-18 23:51
Closing, please reopen if you still have an issue after applying #421 .

**Closed by deadeyegoodwin** 2019-11-18 23:51 UTC
