### ISSUE TITLE
maskrcnn-benchmark pytorch model error

### ISSUE THREAD

**Issue by schyun9212** [NVIDIA/tensorrt-inference-server#1015] opened 2020-01-10 07:05 UTC
**Description**

I made a script model using TorchScript about maskrcnn-benchmark pytorch model.
To make tracing success, some custom operator is added.
When I run trtserver with the model, error occurred caused by the custom operator.

How can I use custom operator?

**TRTIS Information**
What version of TRTIS are you using? r19.12-py3
Are you using the TRTIS container or did you build it yourself? using docker container

**To Reproduce**

1. Make a script model using TorchScript
2. move model.pt to model_repository/1/model.pt
3. run trtserver

**Expected behavior**

```bash
jade@jade-worker:~/Workspace/scripting/t-vi/maskrcnn-benchmark/demo$ docker run --gpus all --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -v$PWD/model_repository:/models nvcr.io/nvidia/tensorrtserver:19.12-py3 /opt/tensorrtserver/bin/trtserver --model-store=/models

===============================
== TensorRT Inference Server ==
===============================

NVIDIA Release 19.12 (build 9147854)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

2020-01-10 06:45:33.193599: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
I0110 06:45:33.220042 1 metrics.cc:160] found 1 GPUs supporting NVML metrics
I0110 06:45:33.225513 1 metrics.cc:169]   GPU 0: GeForce RTX 2080 Ti
I0110 06:45:33.225665 1 server.cc:112] Initializing TensorRT Inference Server
I0110 06:45:33.384186 1 server_status.cc:55] New status tracking for model 'maskrcnn'
I0110 06:45:33.384234 1 model_repository_manager.cc:675] loading: maskrcnn:1
I0110 06:45:33.460471 1 libtorch_backend.cc:224] Creating instance maskrcnn_0_gpu0 on GPU 0 (7.5) using model.pt
E0110 06:45:35.437136 1 model_repository_manager.cc:832] failed to load 'maskrcnn' version 1: Internal: load failed for libtorch model -> 'maskrcnn': 
Unknown builtin op: maskrcnn_benchmark::nms.
Could not find any similar ops to maskrcnn_benchmark::nms. This op may not exist or may not be currently supported in TorchScript.
:
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/amp.py(22): wrapper
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py(27): boxlist_nms
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py(120): forward_for_single_feature_map
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py(140): forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(539): __call__
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py(187): _forward_test
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py(161): forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(539): __call__
/home/jade/Workspace/scripting/t-vi/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py(49): forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/nn/modules/module.py(539): __call__
<ipython-input-3-bdcc77528fb4>(4): single_image_to_top_predictions
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/torch/jit/__init__.py(883): trace
<ipython-input-20-eed77633a86f>(52): <module>
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3319): run_code
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3242): run_ast_nodes
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3051): run_cell_async
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2874): _run_cell
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2848): run_cell
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/zmqshell.py(536): run_cell
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/ipkernel.py(300): do_execute
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/gen.py(209): wrapper
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/kernelbase.py(541): execute_request
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/gen.py(209): wrapper
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/kernelbase.py(268): dispatch_shell
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/gen.py(209): wrapper
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/kernelbase.py(361): process_one
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/gen.py(748): run
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/gen.py(787): inner
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/ioloop.py(743): _run_callback
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/ioloop.py(690): <lambda>
/home/jade/.pyenv/versions/3.7.6/lib/python3.7/asyncio/events.py(88): _run
/home/jade/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py(1782): _run_once
/home/jade/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py(538): run_forever
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/tornado/platform/asyncio.py(148): start
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel/kernelapp.py(563): start
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/traitlets/config/application.py(664): launch_instance
/home/jade/.pyenv/versions/maskrcnn-tracing-t-vi/lib/python3.7/site-packages/ipykernel_launcher.py(16): <module>
/home/jade/.pyenv/versions/3.7.6/lib/python3.7/runpy.py(85): _run_code
/home/jade/.pyenv/versions/3.7.6/lib/python3.7/runpy.py(193): _run_module_as_main
Serialized at code/__torch__.py:627:11
    _118 = annotate(List[Optional[Tensor]],[item1])
    v0 = torch.index(v, _118)
    keep = ops.maskrcnn_benchmark.nms(bbox6, v0, 0.69999999999999996)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    item2 = torch.slice(keep, 0, 0, 1000, 1)
    item3 = torch.to(item2, dtype=4, layout=0, device=torch.device("cpu"), pin_memory=False, non_blocking=False, copy=False)

E0110 06:45:35.437277 1 main.cc:1158] error: creating server: INTERNAL - failed to load all models
```

**Comment by deadeyegoodwin** [comment] 2020-01-13 17:00
TRTIS does support custom operations for TensorRT and Tensorflow, see https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/custom_operation.html#custom-operations

I do not think there is any support for PyTorch custom operations. How is your custom operation defined? In Python? In C/C++?

**Comment by CoderHam** [comment] 2020-01-13 19:56
Custom operators have to be handled as described on this [page]( https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html), operators from cpp extensions without registering them with torch script won’t work. The changes compared to cpp extension are not big though, and that page describes what needs to be done. 
For instance, you can look at torch vision, it is now fully scriptable and uses custom ops https://github.com/pytorch/vision/blob/52b8685bde554501604471337a11578fdf026027/torchvision/csrc/vision.cpp
We will be working towards adding support for custom pytorch ops in TRTIS once we finalize the best way to go about it. If it is urgent I would urge you to try a custom backend that adds support for this specific custom operation to pytorch.

**Comment by schyun9212** [comment] 2020-01-14 03:11
Following the instructions [in the TorchScript document](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html), I registered custom operator implemented in C++.

```cpp
// custom_ops.cpp
#include <torch/script.h>

#include "nms.h"
#include "ROIAlign.h"

static auto registry =
  torch::jit::RegisterOperators()
    .op("maskrcnn_benchmark::nms", &nms)
    .op("maskrcnn_benchmark::roi_align_forward(Tensor input, Tensor rois, float spatial_scale, int pooled_height, int pooled_width, int sampling_ratio) -> Tensor", &ROIAlign_forward);
```
I loaded the registered custom operator in Python.

```python
torch.ops.load_library(os.path.join(LIB_PATH, 'customops.so'))
```
I successfully created a script model using torch.jit.trace.

```python
model = torch.jit.trace(model, (image,))
model.save(MODEL_PATH)
```

Then I placed the model in model repository and ran trtserver.
```bash
docker run --gpus all --rm\
                  --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001\
                  -v$PWD/models:/models\
                  nvcr.io/nvidia/tensorrtserver:19.12-py3\
                  /opt/tensorrtserver/bin/trtserver --model-store=/models

```

I've already referred to [this document](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/custom_operation.html#custom-operations). I placed custom operator shared library in _lib directory. I tried

```bash
docker run --gpus all --rm\
                  -it\
                  --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001\
                  -v$PWD/model_repository:/models\
                  -v$PWD/lib:/_lib\
                  -v/usr/local/cuda-10.1:/usr/local/cuda-10.1\
                  nvcr.io/nvidia/tensorrtserver:19.12-py3
```
Because my PyTorch model uses cuda 10.1, I export path for cuda 10.1

```bash
# In docker container
root@c1f1d596a31e:/opt/tensorrtserver/bin# export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
root@c1f1d596a31e:/opt/tensorrtserver/bin# export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
root@c1f1d596a31e:/opt/tensorrtserver/bin# LD_PRELOAD=/_lib/custom_ops.so trtserver --model-repository=/models
```

Then I meet symbol lookup error.

```bash
trtserver: symbol lookup error: /_lib/custom_ops.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

Is there anything wrong with my process? If the process wasn't wrong, is there no alternative to the PyTorch custom operator right now except to try the custom backend?

**Comment by CoderHam** [comment] 2020-01-14 19:43
The document you referred to above loads the custom ops for TRT and TF model. We are yet to test the support for the pytorch backend. I will keep this thread updated with my progress although the steps you described should have worked.

The reason you receive the undefined symbol error is probably because there is an ABI compatibility issue. I would think this happens because you mount and add cuda 10.1 to path while TRTIS and pytorch inside TRTIS as well uses (and contains pytorch that was built with) 10.2 as of the current release. This may cause a conflict and therefore the undefined symbol error. 

Please share the Cmake file you are using for the build along with the pytorch and gcc version. You should ideally use the same version of pytorch and cuda to avoid such issues.

**Comment by CoderHam** [comment] 2020-01-16 21:18
@schyun9212 I added a test for custom ops in pytorch. It works fine. Have a look at #1031. Additionally the issue of missing symbols could be caused by a pytorch version issue. I would use the NGC container for pytorch (nvcr.io/nvidia/pytorch:19.12-py3) to ensure that TRTIS uses the same version of Pytorch as that used to build the model and custom op. 

I am closing this ticket for now. Please reopen if you follow these steps and are still unable to get the model to load successfully in TRTIS.

**Closed by CoderHam** 2020-01-16 21:18 UTC
