### ISSUE TITLE
Can't use GCS bucket name as model repository root

### ISSUE THREAD

**Issue by jobegrabber** [NVIDIA/tensorrt-inference-server#459] opened 2019-07-14 22:10 UTC
In the current state I am unable to configure a GCS bucket root as a model repository root, i.e. TRTIS is unable to use `gs://somebucket` as the root path for the model repository. `gs://somebucket/somedir` works.
I expect this to be the case since [`ParsePath` of `filesystem`](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/filesystem.cc#L278) will fail if there's no object specified in the path. `ParsePath` is called during the setup via a call to [`IsDirectory` of `filesystem`](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/model_repository_manager.cc#L785) of the model repository.

**Comment by deadeyegoodwin** [comment] 2019-07-15 15:47
It looks like we accidentally dropped GCS support as part of the transition from bazel->cmake and decoupling from TF. We should have caught this error in our release QA process.. well we actually did catch it but mis-attributed it to another issue.

GCS support is restored on the master branch and will be in the 19.07 release. We will update the release notes.

**Closed by deadeyegoodwin** 2019-07-15 15:47 UTC

**Comment by jobegrabber** [comment] 2019-07-15 19:31
Thanks for confirming GCS support is not supported in 1.3.0, @deadeyegoodwin.

For clarification: With `current state` I do mean the state of the `master` branch, specifically @ https://github.com/NVIDIA/tensorrt-inference-server/commit/765c2f1664aeeb3206adc3ab8f8a292874591eb4 - so as far as I can tell the issue of not being able to use the root of a GCS bucket is present in the current development version as well, I tested this with an Docker image built based on this state.
Is the GCS integration still work-in-progress for 19.07?

**Comment by chasein** [comment] 2019-07-15 19:51
fuck you bitches

On Jul 15, 2019 9:47 AM, deadeyegoodwin <notifications@github.com> wrote:

It looks like we accidentally dropped GCS support as part of the transition from bazel->cmake and decoupling from TF. We should have caught this error in our release QA process.. well we actually did catch it but mis-attributed it to another issue.

GCS support is restored on the master branch and will be in the 19.07 release. We will update the release notes.

**Comment by deadeyegoodwin** [comment] 2019-07-15 20:21
@jobegrabber Thanks for the clarification. Not being able to use the root path seems to be a bug in the "current state". We will fix.

**Comment by xprotobeast2** [comment] 2019-07-16 16:57
@jobegrabber I put up a PR for this in #466. Could you let us know if this works for you?

**Comment by jobegrabber** [comment] 2019-07-16 17:17
@xprotobeast2 Thanks! I'll have a look at it in a bit.

**Comment by jobegrabber** [comment] 2019-07-16 19:52
@xprotobeast2 This works for me, thanks a lot!

FYI: As with previous commits based on master, I had to apply the following change otherwise the Docker build would fail complaining that `libonnxruntime.so` already exists:
```diff
diff --git a/Dockerfile b/Dockerfile
index 945b242..d65ea3f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -234,6 +234,7 @@ COPY --from=trtserver_onnx /workspace/onnxruntime/include/onnxruntime \
 COPY --from=trtserver_onnx /workspace/build/Release/libonnxruntime.so.${ONNX_RUNTIME_VERSION} \
      /opt/tensorrtserver/lib/
 RUN cd /opt/tensorrtserver/lib && \
+    rm libonnxruntime.so && \
     ln -s libonnxruntime.so.${ONNX_RUNTIME_VERSION} libonnxruntime.so
 
 # Copy entire repo into container even though some is not needed for
```
I'm still investigating whether this issue stems from my Docker setup, just wanted to mention it for completeness's sake.

**Comment by CoderHam** [comment] 2019-07-16 22:52
@jobegrabber it could be caused by some cache issue. Do you get the same error with the current master if you build using `--no-cache`?

**Comment by jobegrabber** [comment] 2019-07-17 21:28
@CoderHam I did not have the time to check this again with `--no-cache` but with #472 applied it looks good, thanks for looking at it.

**Comment by CoderHam** [comment] 2019-07-17 22:39
Yes I was able to reproduce the error you were getting even with `--no-cache`.  The above patched the aforementioned bug. Happy to help :+1:
