### ISSUE TITLE
Wrong output order retrieval using ensemble model

### ISSUE THREAD

**Issue by SlipknotTN** [NVIDIA/tensorrt-inference-server#274] opened 2019-05-07 12:45 UTC
I think that there is something strange in output order retrieval when using ensembling, which causes the failure of output shape validation.

The ensemble model correctly works if I don't map latest output, problems arises when models inside the ensemble have more than 2 outputs. There is misaligment that causes the failure of this check https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/provider.cc#L434. In particular batch1_backend_shape elements are right (retrieved in the correct order) while expected_shape elements are in the wrong order (3,1,2 instead of 1,2,3).

All works correctly if I call the 3 models separately.

This is my configuration (I'm sorry but I can't provide the real models). Please notice that I have the error on the last model (output 'output_3' for model 'process_cpp' has shape [1] but model configuration specifies shape [10]).

**Ensemble config**

```
name: "chain"
max_batch_size: 4
platform: "ensemble"
ensemble_scheduling {
  step [
    {
      model_name: "model_tensorrt"
      model_version: -1
      input_map {
        key: "input"
        value: "input"
      }
      output_map {
        key: "output"
        value: "maps"
      }
    },
    {
      model_name: "model_tf"
      model_version: -1
      input_map {
        key: "input_maps"
        value: "maps"
      }
      input_map {
        key: "hw"
        value: "hw"
      }
      output_map {
        key: "temp_value_1"
        value: "temp_value_1"
      }
      output_map {
        key: "temp_value_2"
        value: "temp_value_2"
      }
      output_map {
        key: "temp_value_3"
        value: "temp_value_3"
      }
    },
    {
      model_name: "process_cpp"
      model_version: -1
      input_map {
        key: "temp_value_1"
        value: "temp_value_1"
      }
      input_map {
        key: "temp_value_2"
        value: "temp_value_2"
      }
      input_map {
        key: "temp_value_3"
        value: "temp_value_3"
      }
      output_map {
        key: "output_2"
        value: "output_2"
      }
      output_map {
        key: "output_1"
        value: "output_1"
      }
      output_map {
        key: "output_3"
        value: "output_3"
      }
    }
  ]
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 368, 656 ]
  },
  {
    name: "hw"
    data_type: TYPE_INT32
    dims: [ 2 ]
  }
]
output [
  {
    name: "output_2"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ 10, 25, 3 ]
  },
  {
    name: "output_3"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

```

**Model 1 Config**

```
name: "model_tensorrt"
platform: "tensorrt_plan"
max_batch_size: 4
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 368, 656 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 46, 82, 78 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```

**Model 2 Configuration**

```
name: "model_tf"
platform: "tensorflow_graphdef"
max_batch_size: 4
input [
  {
    name: "input_maps"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ -1, -1, 78 ]
  },
  {
    name: "hw"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
output [
  {
    name: "temp_value_1"
    data_type: TYPE_FP32
    dims: [ -1, -1, 26 ]
  },
  {
    name: "temp_value_2"
    data_type: TYPE_FP32
    dims: [ -1, -1, 52 ]
  },
  {
    name: "temp_value_3"
    data_type: TYPE_FP32
    dims: [ -1, -1, 26 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```

**Model 3 Configuration**

```
name: "process_cpp"
platform: "custom"
max_batch_size: 4
default_model_filename: "lib_process.so"
input [
  {
    name: "temp_value_1"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 184, 328, 26 ]
  },
  {
    name: "temp_value_2"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 184, 328, 52 ]
  },
  {
    name: "temp_value_3"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 184, 328, 26 ]
  }
]
output [
  {
    name: "output_2"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ 10, 25, 3 ]
  },
  {
    name: "output_3"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]


```

**Comment by SlipknotTN** [comment] 2019-05-07 16:24
Order of retrieval seems to depend on output_map elements order in ensemble config

**Comment by GuanLuo** [comment] 2019-05-07 16:25
> In particular batch1_backend_shape elements are right (retrieved in the correct order) while expected_shape elements are in the wrong order (3,1,2 instead of 1,2,3).

Are 3, 1, 2 here referencing to output_3, output_1, output_2? In other words, you are observing that output_3 has shape [1], output_1 has shape [10, 25, 3] and output_2 has [10]?

**Comment by GuanLuo** [comment] 2019-05-07 16:27
So if you reorder the output_map specified in ensemble config "in the right way", the outputs will be retrieved with the correct order?

**Comment by SlipknotTN** [comment] 2019-05-08 08:11
> Are 3, 1, 2 here referencing to output_3, output_1, output_2? In other words, you are observing that output_3 has shape [1], output_1 has shape [10, 25, 3] and output_2 has [10]?

Exactly, batch1_backend_shape elements in provider.cc InferResponseProvider::FinalizeResponse function are retrieved in that order.

> And what is the error message returned when the check you mentioned failed? Did it mention the failure came from 3 ("In ensemble 'chain', output 'xxx' for model 'process_cpp'...") or just "output 'xxx' for model 'chain'..."

The exact error client side is
```
tensorrtserver.api.InferenceServerException: [inference:0 9] in ensemble 'chain', output 'output_3' for model 'process_cpp' has shape [1] but model configuration specifies shape [10]
```
And server side the log message is this
```
I0508 08:05:09.602158 1 server.cc:347] Infer failed: in ensemble 'chain', output 'output_3' for model 'process_cpp' has shape [1] but model configuration specifies shape [10]
```

> So if you reorder the output_map specified in ensemble config "in the right way", the outputs will be retrieved with the correct order?

No, I have already tested output maps in the right order (like the posted configuration), but I have noticed that if I change that order, I get a different combination of error in output order retrieval. But in the end I can't get the right order to pass the validation check.

**Comment by GuanLuo** [comment] 2019-05-08 20:47
It may not be relevant, but I notice that in your ensemble config, you are mapping "temp_value_2" to "temp_value_1" for "process_cpp". Is this what you intended to do?
```
input_map {
    key: "temp_value_1"
    value: "temp_value_2"
}
```

**Comment by SlipknotTN** [comment] 2019-05-09 08:23
> It may not be relevant, but I notice that in your ensemble config, you are mapping "temp_value_2" to "temp_value_1" for "process_cpp". Is this what you intended to do?
> 
> ```
> input_map {
>     key: "temp_value_1"
>     value: "temp_value_2"
> }
> ```
> 
> **UPDATE:** I suppose this is just typo when you create the issue. Otherwise the ensemble won't be created as there is "ensemble tensor" declared but not used (temp_value_1)

Yes, it was an error when I created the issue...

**Comment by SlipknotTN** [comment] 2019-05-10 16:24
I can't recreate a simple example to reproduce the error, but I have noticed that model_config output_maps order is different w.r.t. config.prototxt. You can see it from api/status or debugging model_config in model_repository_manager.cc, same order is propagated to ensemble_scheduler.cc.

I have noticed that also the second model output maps inside the ensemble are retrieved in the wrong order in model_config object (while in api/status is ok), but in tensorflow/base_backend.cc is resorted while you iterate over the set of required_outputs (maybe order is not important for TensorFlow models).

Order seems to be retrieved in alphabetically for model 3 (custom cpp), but it is not true for model 2, in both case is different w.r.t. config file.
I have updated the config in the first post, output_maps of model 2 are in alphabetical order and output_maps of model 3 not, like my real case.
Unfortunately there is something else, because if I change names to respect always the alphabetical order in model3, the error persists.

Example of mapping of last model and ensemble output:

```
output_map {
  key: "output_2"
  value: "output_2"
}
output_map {
  key: "output_1"
  value: "output_1"
 }
 output_map {
   key: "output_3"
   value: "output_3"
}

...

{
  name: "output_2"
  data_type: TYPE_INT32
  dims: [ 1 ]
},
{
  name: "output_1"
  data_type: TYPE_FP32
  dims: [ 10, 25, 3 ]
},
{
  name: "output_3"
  data_type: TYPE_FP32
  dims: [ 10 ]
}

```

**Comment by GuanLuo** [comment] 2019-05-10 16:43
In the expected behavior, the output map's order should be insensitive, since the backends retrieve tensors by names and the ensemble scheduler looks up corresponding input/output names based on the mapping. However, since the order does matter as you mentioned, it implies that the ensemble scheduler may rely on the order of the mapping while it shouldn't have. I will look into that.

In the meantime, I will try to reproduce the error by creating a model repository with the same layout (but with vanilla models).

**Comment by GuanLuo** [comment] 2019-05-10 16:57
And also for your reference, I tried to use the following model repository layout but I can't reproduce the error.
<details><summary>Ensemble model "chain"</summary>
<p>

```
name: "chain"
max_batch_size: 4
platform: "ensemble"
ensemble_scheduling {
  step [
    {
      model_name: "single_out_identity"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "INPUT0"
      }
      output_map {
        key: "OUTPUT0"
        value: "temp_value_0"
      }
    },
    {
      model_name: "single_out_2d_identity"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "INPUT1"
      }
      output_map {
        key: "OUTPUT0"
        value: "temp_value_1"
      }
    },
    {
      model_name: "single_out_identity"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "INPUT2"
      }
      output_map {
        key: "OUTPUT0"
        value: "temp_value_2"
      }
    },
    {
      model_name: "multi_out_identity"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "temp_value_0"
      }
      input_map {
        key: "INPUT1"
        value: "temp_value_1"
      }
      input_map {
        key: "INPUT2"
        value: "temp_value_2"
      }
      output_map {
        key: "OUTPUT2"
        value: "OUTPUT2"
      }
      output_map {
        key: "OUTPUT1"
        value: "OUTPUT1"
      }
      output_map {
        key: "OUTPUT0"
        value: "OUTPUT0"
      }
    }
  ]
}
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  },
  {
    name: "INPUT1"
    data_type: TYPE_FP32
    dims: [ 4, 8 ]
  },
  {
    name: "INPUT2"
    data_type: TYPE_FP32
    dims: [ 8 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  },
  {
    name: "OUTPUT1"
    data_type: TYPE_FP32
    dims: [ 4, 8 ]
  },
  {
    name: "OUTPUT2"
    data_type: TYPE_FP32
    dims: [ 8 ]
  }
]
```


</p>
</details>
<details><summary>single_out_identity</summary>
<p>

```
name: "single_out_identity"
platform: "custom"
max_batch_size: 4
default_model_filename: "libidentity.so"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

</p>
</details>
<details><summary>single_out_2d_identity</summary>
<p>

```
name: "single_out_2d_identity"
platform: "custom"
max_batch_size: 4
default_model_filename: "libidentity.so"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

</p>
</details>
<details><summary>multi_out_identity</summary>
<p>

```
name: "multi_out_identity"
platform: "custom"
max_batch_size: 4
default_model_filename: "libidentity.so"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]

input [
  {
    name: "INPUT1"
    data_type: TYPE_FP32
    dims: [ 4, 8 ]
  }
]
output [
  {
    name: "OUTPUT1"
    data_type: TYPE_FP32
    dims: [ 4, 8 ]
  }
]

input [
  {
    name: "INPUT2"
    data_type: TYPE_FP32
    dims: [ 8 ]
  }
]
output [
  {
    name: "OUTPUT2"
    data_type: TYPE_FP32
    dims: [ 8 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

</p>
</details>

**Comment by SlipknotTN** [comment] 2019-05-13 13:47
Thank you for your time, I have created a dummy example with the same shapes of my real models and the error can be reproduced.

[Models](https://drive.google.com/file/d/1y9pP1OozsqYwA2dwfvWYi90Pq-lVZsT7/view?usp=sharing)

Linked file contains:
- Ensemble model
- Model 1 (TF instead of TensorRT like my first example, but shapes are the same)
- Model 2 (TF)
- Model 3 Cpp
- Python file to call the server and reproduce the error

How to launch the python file:
```
python test_postprocess_trtis_dummy_chain.py
-i <image_path> \
-m dummy_chain \
-s RANGE0.5 \
-cs BGR \
-p HTTP \
-r 1 \
-v -u <server_address>
```

This is the error I get:
```
tensorrtserver.api.InferenceServerException: [inference:0 3] in ensemble 'dummy_chain', output 'output_c' for model 'dummy_cpp' has shape [1] but model configuration specifies shape [10]
```
No problem if I call submodels separately.

**Comment by GuanLuo** [comment] 2019-05-13 22:27
Is your custom model assuming that the outputs are requested in certain order? From my experiments, it seems like the `dummy_cpp` model you provided will always call `GetOutput()` with a specific order of output shapes (first set one output with [1], then another output with [10, 25, 3], then last output with [10]).

TRTIS doesn't guarantee that the outputs requested in the "request header" are in the order specified in "config.pbtxt". Here I am imagining that your custom model calls `output_fn` with `required_output_names` from payload struct and the shape from model config? If that is the case then you can try to call `output_fn` with both output names and shape directly from model config and see if the issue persists.

<details><summary>Experiment detail</summary>
<p>

- I added print statement [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/backends/custom/custom_backend.cc#L471) to check the output name and shape.
- Added another ensemble model ("dummy_short_chain") that only chains the first two model together to separate the third model out
- I used "ordered dict" so that I can change the order of the required output.

<details><summary>config.pbtxt for dummy_short_chain</summary>
<p>

```
name: "dummy_short_chain"
max_batch_size: 4
platform: "ensemble"
ensemble_scheduling {
  step [
    {
      model_name: "model_1_dummy_tf"
      model_version: -1
      input_map {
        key: "input"
        value: "input"
      }
      output_map {
        key: "output"
        value: "maps"
      }
    },
    {
      model_name: "model_2_dummy_tf"
      model_version: -1
      input_map {
        key: "input_maps"
        value: "maps"
      }
      input_map {
        key: "hw"
        value: "hw"
      }
      output_map {
        key: "temp_value_1"
        value: "output_a"
      }
      output_map {
        key: "temp_value_2"
        value: "output_b"
      }
      output_map {
        key: "temp_value_3"
        value: "output_c"
      }
    }
  ]
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 368, 656, 3 ]
  },
  {
    name: "hw"
    data_type: TYPE_INT32
    dims: [ 2 ]
  }
]
output [
  {
    name: "output_a"
    data_type: TYPE_INT32
    dims: [ -1, -1, 26 ]
  },
  {
    name: "output_b"
    data_type: TYPE_FP32
    dims: [ -1, -1, 52 ]
  },
  {
    name: "output_c"
    data_type: TYPE_FP32
    dims: [ -1, -1, 26 ]
  }
]
```

</p></details>

```Python
# run "dummy_short_chain" to get "results" ...
# create context to send request to "dummy_cpp"
to_dummy = TRTISClient(protocol=args.protocol, url=args.url, model_name="dummy_cpp",
                       streaming=args.streaming, model_version=args.model_version,
                       scaling=args.scaling, colorspace=args.colorspace,
                       verbose=args.verbose)
to_dummy.parse_model()

# Same order as in config.pbtxt {output_b, output_a, output_c}
output_requested = OrderedDict()
output_requested[to_dummy.output_names[0]] = InferContext.ResultFormat.RAW
output_requested[to_dummy.output_names[1]] = InferContext.ResultFormat.RAW
output_requested[to_dummy.output_names[2]] = InferContext.ResultFormat.RAW

res = to_dummy.ctx.run(
    {to_dummy.input_names[0]: result["output_a"],
     to_dummy.input_names[1]: result["output_b"],
     to_dummy.input_names[2]: result["output_c"]},
    output_requested, 1)
```
```
# print from server
setting output 'output_b' with shape '[1,1]
setting output 'output_a' with shape '[1,10,25,3]
setting output 'output_c' with shape '[1,10]

```
Changing requested output order will get different print output and exception:
```Python
...
# Now {output_a, output_c, output_b}
output_requested = OrderedDict()
output_requested[to_dummy.output_names[1]] = InferContext.ResultFormat.RAW
output_requested[to_dummy.output_names[2]] = InferContext.ResultFormat.RAW
output_requested[to_dummy.output_names[0]] = InferContext.ResultFormat.RAW

res = to_dummy.ctx.run(
    {to_dummy.input_names[0]: result["output_a"],
     to_dummy.input_names[1]: result["output_b"],
     to_dummy.input_names[2]: result["output_c"]},
    output_requested, 1)
```
```
setting output 'output_a' with shape '[1,1]
setting output 'output_c' with shape '[1,10,25,3]
setting output 'output_b' with shape '[1,10]

tensorrtserver.api.InferenceServerException: [inference:0 147] output 'output_a' for model 'dummy_cpp' has shape [1] but model configuration specifies shape [10,25,3]
```

</p></details>

**Comment by SlipknotTN** [comment] 2019-05-14 10:18
Thank you, now the problem is solved.

The problem was the output order in the request different w.r.t. model config order. Now in my lib I support any order and it works. My error was to retrieve output name from request order and shape/size information from model config order.

**Comment by GuanLuo** [comment] 2019-05-14 16:27
Good to know that the problem is resolved. Closing the issue.

**Closed by GuanLuo** 2019-05-14 16:27 UTC
