### ISSUE TITLE
I got a problem when I use trtis client

### ISSUE THREAD

**Issue by rithd** [NVIDIA/tensorrt-inference-server#971] opened 2019-12-18 07:43 UTC
**Description**
when i use infer_ctx.run to inference a tensorflow graphdef model, the client displayed errors like:

tensorrtserver.api.InferenceServerException: [inference:0 92] 2 root error(s) found.
  (0) Invalid argument: input must be 4-dimensional[1,1,248,400,3]
         [[{{node Preprocessor/map/while/ResizeToRange/resize_images/ResizeBilinear}}]]
         [[SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_22/iou_threshold/_1489]]
  (1) Invalid argument: input must be 4-dimensional[1,1,248,400,3]
         [[{{node Preprocessor/map/while/ResizeToRange/resize_images/ResizeBilinear}}]]

my input tensor's shape is [1,248,400,3] instead of [1,1,248,400,3]. Why does it add an extra dimension？

Please help me to fix it :) 
thanks a lot
 

**TRTIS Information**
I use docker to run trits and client. The versions are "nvcr.io/nvidia/tensorrtserver:19.09-py3" and "trtis_client:19.07.x "

**To Reproduce**
Run the client to inference the model.

**Expected behavior**
inference successfuly

**Comment by bezero** [comment] 2019-12-18 09:25
The first dimension is the batch size. For instance:
```py
# Run inference
ctx = InferContext(url, protocol, model_name)
results = ctx.run(
    {input_name: input_list},
    {output_name: InferContext.ResultFormat.RAW},
    batch_size)
```
In here, if `input_list` is a list of single input of `[1,248,400,3]` shape, this will become `[1,1,248,400,3]`, if a list of 2 than `[2,1,248,400,3]`. What I understand from your input is that you are trying to send a single image with `[248,400,3]` dims. Try to get rid of first dim. 
```
input_list = [np.squeeze(input_image)]
```

**Comment by rithd** [comment] 2019-12-18 10:16
yeah, i really want to send a single picture but my model input shape is [-1, -1, -1, 3] which can be sent any number, height, width 3 channels picture. In fact, my code is :

image = Image.open(FLAGS.image_filename)
    image_np = np.array(image).astype(np.uint8)
    image_np = np.expand_dims(image_np, axis=0)


I use np.expand_dims to fit the first dimension of my model input, otherwise it will occur the error like:

 "tensorrtserver.api.InferenceServerException: [inference:0 97] unexpected shape for input 'image_tensor' for model 'sign_detect'. Expected [-1,-1,-1,3], got [248,400,3]"

it looks like lacking batchsize dimension. But it is conflict for the error in front of.

**Comment by bezero** [comment] 2019-12-18 10:32
Can you please share your `config.pbtxt`? and if possible code snippet of how you send inference request using `InferContext`?

**Comment by rithd** [comment] 2019-12-19 01:38
my config.pbtxt is 

name: "sign_detect"
platform: "tensorflow_graphdef"
max_batch_size: 8
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    dims: [ -1, -1, -1, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [] }
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [] }
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [] }
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [] }
  }
]

and here is my client code:

    model_name = FLAGS.model_name
    model_version = -1
    batch_size = 1

    # Create a health context, get the ready and live state of server.
    health_ctx = ServerHealthContext(FLAGS.url, protocol,
                                     http_headers=FLAGS.http_headers, verbose=FLAGS.verbose)
    print("Health for model {}".format(model_name))
    print("Live: {}".format(health_ctx.is_live()))
    print("Ready: {}".format(health_ctx.is_ready()))

    # Create a status context and get server status
    status_ctx = ServerStatusContext(FLAGS.url, protocol, model_name,
                                     http_headers=FLAGS.http_headers, verbose=FLAGS.verbose)
    print("Status for model {}".format(model_name))
    print(status_ctx.get_server_status())

    # Create the inference context for the model.
    infer_ctx = InferContext(FLAGS.url, protocol, model_name, model_version,
                             http_headers=FLAGS.http_headers, verbose=FLAGS.verbose)

    image = Image.open(FLAGS.image_filename)
    image_np = np.array(image).astype(np.uint8)
    image_np = np.expand_dims(image_np, axis=0)

    # Send inference request to the inference server. Get results for
    # both output tensors.
    result = infer_ctx.run({ 'image_tensor' : ([image_np]) },
                           { 'detection_boxes' : InferContext.ResultFormat.RAW,
                             'detection_classes' : InferContext.ResultFormat.RAW,
                             'detection_scores' : InferContext.ResultFormat.RAW,
                             'num_detections' : InferContext.ResultFormat.RAW},
                           batch_size)

**Comment by bezero** [comment] 2019-12-19 05:06
[Here](https://github.com/NVIDIA/tensorrt-inference-server/issues/217#issuecomment-481968683) you can find an example of what you are trying to accomplish. From your code, in config change input dims to:
```
input [
{
name: "image_tensor"
data_type: TYPE_UINT8
dims: [ -1, -1, 3 ]
}
]
```
and in your client code remove this line: `image_np = np.expand_dims(image_np, axis=0)`.
For `output` dims, you might get some errors too.

**Comment by rithd** [comment] 2019-12-19 06:29
It works,thanks a lot.
But, could you tell me though my model input shapes is 
{"shape":{"dim":[{"size":-1},{"size":-1},{"size":-1},{"size":3}]}}
in tensorboard, the shape writen in config.pbtxt is [ -1, -1, 3 ] and it can be started successfully?

**Comment by bezero** [comment] 2019-12-19 06:41
@rithd in TRTIS if you set `max_batch_size: 0` than you can set the exact dimension `dims: [ 1,-1, -1, 3 ]`. Here if you notice we set first dim to be ***1***, since in this case ***-1*** is not allowed. However, this means that your deployed model will not be supporting batch inference. In your case, when you set `max_batch_size: 8`, it means that you can send up to 8 images at once and it is batched accordingly. For example you can send 4 requests:
```
result = infer_ctx.run({ 'image_tensor' : ([image_np, image_np, image_np, image_np]) },
                       { 'detection_boxes' : InferContext.ResultFormat.RAW,
                         'detection_classes' : InferContext.ResultFormat.RAW,
                         'detection_scores' : InferContext.ResultFormat.RAW,
                         'num_detections' : InferContext.ResultFormat.RAW},
                       4)
```

**Comment by rithd** [comment] 2019-12-19 06:51
I think my model's input is 4 dimensions (and the first dimensions is actually batch size) but it should have nothing to do with trtis. Trtis should cannot mention the first dimension as batch size. Is that true?

**Comment by bezero** [comment] 2019-12-19 07:03
Yes, your model is 4 dimensional and the first dimension is the batch size. It is important for TRTIS, as it determines whether your model supports batch inference or not. In your case, having batch size -1 means you can specify any max_batch_size and TRTIS will support all batch sizes up to that number. On the other hand, if your model did not suport any batch size, you should set max_batch_size to 0 and TRTIS will know that your model does not support batching. For example, let's say your model only supported batch size 3 and had dim `dims: [ 3,-1, -1, 3 ]` than you would have:
```
max_batch_size: 0
input [
{
name: "image_tensor"
data_type: TYPE_UINT8
dims: [ 3, -1, -1, 3 ]
}
]
```

**Comment by rithd** [comment] 2019-12-19 07:23
So trtis will think the first dimension as batch size automatically. If model input has 4 dimensions, in config it should have 3.If it has 3, in config it has 2?

**Comment by bezero** [comment] 2019-12-19 07:28
@rithd If your 1st dim is batch size than yes.

**Comment by rithd** [comment] 2019-12-19 07:32
Alright~
And I have another model, it input is only one pic like [-1, -1, 3]. Then my config should like:


max_batch_size: 0
input [
{
name: "image_tensor"
data_type: TYPE_UINT8
dims: [ -1, -1, 3 ]
}
]

When max_batch_size=0, the first dimension will not be determined as batchsize, is it?

**Comment by bezero** [comment] 2019-12-19 07:43
@rithd Yes, I think this config should work

**Comment by rithd** [comment] 2019-12-19 07:43
thanks a lot :)

**Comment by rithd** [comment] 2019-12-24 08:15
there is another error:

 "tensorrtserver.api.InferenceServerException: [inference:0 22] unexpected shape for output 'num_detections', model configuration shape is [1], inference shape is [1]"

and my config is  

 {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
 }

the dims is [1], why does it occure?

**Comment by rithd** [comment] 2019-12-26 02:30
@bezero 
could you help me, please

**Comment by bezero** [comment] 2019-12-26 06:16
@rithd Unfortunately, I don't know why. Try to use `dims: 1` instead of `dims: [ 1 ]`.

**Comment by GuanLuo** [comment] 2019-12-26 23:35
The error message here is somewhat misleading. the model config shape reported is without batch dimension while the inference shape reported is the full shape, include batch dimension if allow batching.
So, the output "num_detections" of the model seems to have full shape [ batch_size ], and the model config for it in full shape is [ batch_size, 1]. You should try to specify the reshape field of the output in model config so that TRTIS will validate the output shape using the reshape value instead:
```protobuf
{
   name: "num_detections"
   data_type: TYPE_FP32
   dims: [ 1 ]
   reshape: { shape: [] }
}
```

**Comment by rithd** [comment] 2019-12-27 02:32
@GuanLuo 
that works
thx

**Comment by rithd** [comment] 2019-12-27 02:36
"reshape: { shape: [] }"

Does this mean that the output can be any dims?

**Comment by GuanLuo** [comment] 2019-12-27 18:58
No, that means the full shape will be interpret as [ batch_size ] instead of [ batch_size, 1 ] when validating the output shape. See the [documentation](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html#reshape) for detail.

**Comment by rithd** [comment] 2019-12-30 03:24
Thanks.
Another question is that I found the result of a same detection model which ran on TRTIS is different from running directly.The score reduced from 9.99 to 5.51 so that the object couldn't be detected. The model is a tensorflow frozen pb model and I have shown you its config.

**Comment by rithd** [comment] 2020-01-02 01:31
@bezero @GuanLuo 
Please look at this, and happy new year~

**Comment by GuanLuo** [comment] 2020-01-02 17:01
Can you provide steps to reproduce it? And what is the script, and TF version, you used to run directly? It will also be helpful if you can share your model

**Comment by rithd** [comment] 2020-01-03 02:50
The model is secret-involved so I can't provide for you, sorry for that :(
But the model is mostly like a tensorflow object detection model and the input/output has been displayed above.
And the code I run it directly is that:

def __init__(self, model_path=None):
    if os.path.exists(model_path):
            # Load a frozen TF model
            detection_graph = tf.Graph()
            with detection_graph.as_default():
                od_graph_def = tf.GraphDef()
                with tf.gfile.GFile(model_path, 'rb') as fid:
                    serialized_graph = fid.read()
                    od_graph_def.ParseFromString(serialized_graph)
                    tf.import_graph_def(od_graph_def, name='')

            tf_config = tf.ConfigProto()
            tf_config.gpu_options.per_process_gpu_memory_fraction = 0.1
            self.sess = tf.Session(graph=detection_graph, config=tf_config)
            self.image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
            self.boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
            self.scores = detection_graph.get_tensor_by_name('detection_scores:0')
            self.classes = detection_graph.get_tensor_by_name('detection_classes:0')
            self.num_detections = detection_graph.get_tensor_by_name('num_detections:0')
            print('load weights from', model_path)

def predict(self, image):
        image_np = np.array(image).astype(np.uint8)
        image_np = np.expand_dims(image_np, axis=0)

        (boxes, scores, classes, num_detections) = self.sess.run(
            [self.boxes, self.scores, self.classes, self.num_detections],
            feed_dict={self.image_tensor: image_np})
        boxes = np.squeeze(boxes)
        classes = np.squeeze(classes).astype(np.int32)
        scores = np.squeeze(scores)
        cond = np.column_stack([classes == 4, scores > 0.9]).all(axis=1)

The code of trtis client I have writen above.
My TF version is 1.6.0.


Thanks.

**Comment by deadeyegoodwin** [comment] 2020-01-03 18:51
Have you verified that the image tensor you are sending to TRTIS is the same as the one going to TF? Accuracy difference sometimes occur if the image channels or normalization are not as expected by the model.

**Comment by rithd** [comment] 2020-01-06 07:29
The input image tensors are same in TRTIS client and my TF client. That is :

    image = Image.open(FLAGS.image_filename)
    image_np = np.array(image).astype(np.uint8)

And the result shapes are also same.The only different between those are scores decreasing.

**Comment by deadeyegoodwin** [comment] 2020-01-08 00:47
It will be hard for us to help without being able to reproduce. One thing to keep in mind is that TF is usually, but not always backwards compatible. You said you are using TF 1.6 to build and run the model? That is a very old TF. You are using a more recent TF in the TRTIS version you are using. You can look here to see the TF used in each TRTIS: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

Can you try building and running your model using a recent TF (ideally the one included in the version of TRTIS you are using, which for TRTIS 1.9.0 is TF  1.15.0 as shown here: https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-12.html#rel_19-12)

**Closed** 2020-02-03 18:26 UTC
