### ISSUE TITLE
branch r20.02  ubuntu 1604 build error

### ISSUE THREAD

**Issue by 121786404** [NVIDIA/tensorrt-inference-server#1148] opened 2020-02-29 10:45 UTC
**Description**

**TRTIS Information**
What version of TRTIS are you using?
Are you using the TRTIS container or did you build it yourself?

**To Reproduce**

**Expected behavior**

src/core/backend_context.cc:434:26: error: converting to ‘std::tuple<long unsigned int, long unsigned int, std::vector<std::pair<long unsigned int, nvidia::inferenceserver::MutableMemory*>, std::allocator<std::pair<long unsigned int, nvidia::inferenceserver::MutableMemory*> > > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {long unsigned int, long unsigned int, std::vector<std::pair<long unsigned int, nvidia::inferenceserver::MutableMemory*>, std::allocator<std::pair<long unsigned int, nvidia::inferenceserver::MutableMemory*> > >}]’
       pinned_buffer_info = {output_offset + expected_byte_size, 0, {}};

**Comment by deadeyegoodwin** [comment] 2020-03-02 22:18
We will take a look. We primarily test on Ubuntu 18.04 so perhaps related to older compiler/stdlib in 16.04.

**Comment by GuanLuo** [comment] 2020-03-04 02:03
@121786404 can you try the code change in #1155 and see if the issue is resolved?

**Comment by GuanLuo** [comment] 2020-03-06 18:35
Closing the issue. Please re-open it if the issue remains

**Closed by GuanLuo** 2020-03-06 18:35 UTC
