### ISSUE TITLE
GPU memory didn't clean up as expected

### ISSUE THREAD

**Issue by rtrobin** [NVIDIA/tensorrt-inference-server#992] opened 2019-12-27 09:17 UTC
**Description**
GPU memory didn't clean up as expected after several infer requests.

**TRTIS Information**
nvcr.io/nvidia/tensorrtserver:19.12-py3
nvcr.io/nvidia/tensorrtserver:19.12-py3-clientsdk

**To Reproduce**
gpu: 1080ti

server:
Pull the image, run container, fetch example models, run trtserver, all as [doc](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/run.html#running-the-server) said.

client:
Pull the image, run command twice.
`image_client -m resnet50_netdef -s INCEPTION -b 64 /workspace/images/mug.jpg`

**Expected behavior**
It should be exact same behavior for both run.

**Actual behavior**
After trtis launches, the gpu usage is shown as below.
![image](https://user-images.githubusercontent.com/8224989/71510966-a03c4d00-28cb-11ea-93c0-84951c270141.png)

Run inference command first time. It works as expected. It shows 64 lines of same image and same result. The result and gpu usage are shown as below.
![image](https://user-images.githubusercontent.com/8224989/71511036-e09bcb00-28cb-11ea-80cf-7dbb1dba2a3a.png)
![image](https://user-images.githubusercontent.com/8224989/71511080-0aed8880-28cc-11ea-8e44-45b880aebb03.png)

Run inference command second time. It failed with 'out of memory'.
``` bash
root@tangyijun:/workspace# image_client -m resnet50_netdef -s INCEPTION -b 64 /workspace/images/mug.jpg 
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
failed sending synchronous infer request: [inference:0 12] INTERNAL - failed to run model 'resnet50_netdef': [enforce fail at context_gpu.cu:496] error == cudaSuccess. 2 vs 0. Error at: /tmp/pip-req-build-aedx9bpx/caffe2/core/context_gpu.cu:496: out of memory
Error from operator: 
input: "gpu_0/res3_1_branch2a_bn" input: "gpu_0/res3_1_branch2b_w" output: "gpu_0/res3_1_branch2b" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 device_id: 0 } engine: ""frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x78 (0x7fc7edae5bd8 in /opt/tensorrtserver/lib/libc10.so)
frame #1: <unknown function> + 0x2ebb793 (0x7fc7f0bba793 in /opt/tensorrtserver/lib/libtorch.so)
frame #2: <unknown function> + 0x2fbde5e (0x7fc7f0cbce5e in /opt/tensorrtserver/lib/libtorch.so)
frame #3: caffe2::empty(c10::ArrayRef<long>, c10::TensorOptions) + 0x56e (0x7fc7f25156de in /opt/tensorrtserver/lib/libtorch.so)
frame #4: <unknown function> + 0x307c9c8 (0x7fc7f0d7b9c8 in /opt/tensorrtserver/lib/libtorch.so)
frame #5: <unknown function> + 0x308abfa (0x7fc7f0d89bfa in /opt/tensorrtserver/lib/libtorch.so)
frame #6: <unknown function> + 0x62ea4bb (0x7fc7f3fe94bb in /opt/tensorrtserver/lib/libtorch.so)
frame #7: <unknown function> + 0x62dce00 (0x7fc7f3fdbe00 in /opt/tensorrtserver/lib/libtorch.so)
frame #8: <unknown function> + 0x3085c63 (0x7fc7f0d84c63 in /opt/tensorrtserver/lib/libtorch.so)
frame #9: caffe2::SimpleNet::Run() + 0x1ba (0x7fc7f24d5f6a in /opt/tensorrtserver/lib/libtorch.so)
frame #10: caffe2::Workspace::RunNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x11e (0x7fc7f252c58e in /opt/tensorrtserver/lib/libtorch.so)
frame #11: <unknown function> + 0x47e0ac7 (0x7fc7f24dfac7 in /opt/tensorrtserver/lib/libtorch.so)
frame #12: <unknown function> + 0x20425b (0x7fc888a3e25b in /opt/tensorrtserver/lib/libtrtserver.so)
frame #13: <unknown function> + 0x8a8f4 (0x7fc8888c48f4 in /opt/tensorrtserver/lib/libtrtserver.so)
frame #14: <unknown function> + 0x200232 (0x7fc888a3a232 in /opt/tensorrtserver/lib/libtrtserver.so)
frame #15: <unknown function> + 0xa10e1 (0x7fc8888db0e1 in /opt/tensorrtserver/lib/libtrtserver.so)
frame #16: <unknown function> + 0xbd66f (0x7fc887f2a66f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #17: <unknown function> + 0x76db (0x7fc8886226db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #18: clone + 0x3f (0x7fc8875e788f in /lib/x86_64-linux-gnu/libc.so.6)
```

![image](https://user-images.githubusercontent.com/8224989/71511252-9c5cfa80-28cc-11ea-8641-a7171dba14e1.png)

It seems trtis doesn't clean up gpu memory after inference request.

**Comment by GuanLuo** [comment] 2019-12-27 18:59
@CoderHam is this related to the Pytorch issue?

**Comment by CoderHam** [comment] 2019-12-27 19:06
Yes, this could be caused by the thread specific caching issue we had seen easier. Are you using multiple instances of the resnet50? If not this may be another issue.

**Comment by GuanLuo** [comment] 2019-12-27 22:32
@CoderHam Don't we have one perf test that shows high GPU memory usage for both Caffe and Pytorch model? Does that only happen in multiple instances case?

**Comment by rtrobin** [comment] 2019-12-30 02:06
@CoderHam Yes, it uses 4 instances of the resnet50 as default.

**Comment by xiaoqiao728295** [comment] 2020-01-14 06:41
@rtrobin I had the same problem with you, do you got any methods to solve that problem?

**Comment by rtrobin** [comment] 2020-01-14 07:33
@xiaoqiao728295 I don't know how to fix this issue. But I would suggest you to adjust instance number and max batch size. Make sure `instance number` * `max batch size` < `gpu memory`.

**Comment by xiaoqiao728295** [comment] 2020-01-14 07:51
thanks for your reply, but every time when i sent a request, the cost of  GPU memory added and didn't clean up, after a while, got out of memory error. Maybe some parameters can be set to clean up the memory automatically？

**Comment by deadeyegoodwin** [comment] 2020-01-14 17:31
@rtrobin Did you try changing the model configuration so that it uses only a single instance? My suspicion is that each instance uses about 5MB of memory that is dynamically allocated the first time an instance is used. It could be that the netdef/pytorch backend is retaining that allocation for performance reasons so that the next inference can reuse it. Inference requests a semi-round-robin assigned to instances so it seems that your requests get assigned to different instances, each of which needs ~5MB of GPU memory.

Caffe2 netdef is semi-deprecated and PyTorch backend in general isn't the best for inference. Depending on what you are trying to do I would suggest the ONNX or TensorRT backend.

**Comment by rtrobin** [comment] 2020-01-15 01:58
@deadeyegoodwin Thanks for the information. I have tried one single instance, which seems working fine. That is why I guessed, if `instance number` * `max batch size` < `gpu memory`, it should be fine.

@xiaoqiao728295 Are you using one single instance?

**Comment by xiaoqiao728295** [comment] 2020-01-15 07:16
@rtrobin yes, it seems fine, thank you very much. But after inference, the memory cost didn't clean up. if i have several instances in a gpu, i have to estimate the memory of each instances cost when inferencing, which seems not very smart.

**Comment by rtrobin** [comment] 2020-01-15 09:41
@xiaoqiao728295 The cost of gpu memory allocation or free is huge compared to computation. It is better to keep the weights and tensors in memory if possible. That is why multiple instance will cost multiple memory. For your case, if you have multiple instances which exceeds gpu memory limitation, you'd better check the model status and load/unload model manually. Check doc. https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/http_grpc_api.html#section-api-model-control

**Comment by xiaoqiao728295** [comment] 2020-01-15 10:18
@rtrobin OK, thank you very much.

**Closed** 2020-01-15 16:47 UTC
