### ISSUE TITLE
Incremental Builds failed

### ISSUE THREAD

**Issue by pwlazy** [NVIDIA/tensorrt-inference-server#235] opened 2019-04-17 09:10 UTC
according to the document( https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.htm)

 i built the docker image successfully by the script  "docker build --pull -t tensorrtserver_build --target trtserver_build ."

i start the docker image and enter the container to perform an incremental server build by the script "bazel build -c opt --config=cuda src/servers/trtserver" , it works too!

but i want to build a debug version , so i executed "bazel build -c dgb --config=cuda src/servers/trtserver" , it failed, and try again, it's the same

the error is as below
`1 error detected in the compilation of "/tmp/tmpxft_00006093_00000000-10_pad_op_gpu.cu.compute_75.cpp1.ii".
ERROR: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/core/kernels/BUILD:879:1: output 'external/org_tensorflow/tensorflow/core/kernels/_objs/pad_op_gpu/pad_op_gpu.cu.pic.o' was not created
ERROR: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/org_tensorflow/tensorflow/core/kernels/BUILD:879:1: not all outputs were created or valid
Target //src/servers:trtserver failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2906.580s, Critical Path: 82.32s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 3590 processes: 3590 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully`

------------------------
another question , the building is so time consuming， i  didn't change any code, it's the same  time consuming with the first building

can the  building way with cmake   be supported?

**Comment by GuanLuo** [comment] 2019-04-17 16:55
It looks like error during the TensorFlow compilation. I usually build the debug version with `--copt -g` and it can build without throwing errors. The compete command I use is: `bazel build --strip never -c opt --copt -g --config=cuda src/servers/trtserver`.

The rebuild using the same command is fast, but as mentioned [here](https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode), "Bazel uses a different output directory for each different compilation mode, so you can switch between modes without needing to do a full rebuild every time." So I think if you change it back to `-c opt`, the building will take less time than the first building.

We are planing to support building with cmake.

**Comment by pwlazy** [comment] 2019-04-18 06:48
the command works! thanks!

**Comment by GuanLuo** [comment] 2019-04-19 00:38
Are you running gdb inside docker container? If so, adding `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined` in `docker run ...` command may resolve the issue.
https://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted#comment62818827_35860527

**Comment by pwlazy** [comment] 2019-04-22 06:05
i executed the scrpit 
 ```
sudo nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864  -p8000:8000 -p8001:8001 -p8002:8002 -it -v /home/xxx/work/model_repository:/models --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --name trt_dbg tensorrtserver_build
```
to start the built docker image

then i enter the container, execute 
```
bazel build --strip never -c opt --copt -g --config=cuda src/servers/trtserver
```

it 's ok

at last , i used "gdb --tui /opt/tensorrtserver/bin/trtserver" to debug trtserver

the error is as below the same with before
```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bazel-bin/src/servers/trtserver...done.
(gdb) set args --model-store=/models
(gdb) start
Temporary breakpoint 1 at 0x6262a0: file src/servers/main.cc, line 67.
Starting program: /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/inference_server/bazel-out/k8-opt/bin/src/servers/trtserver --model-store=/models
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x6262a0
```

**Comment by CoderHam** [comment] 2019-04-24 21:50
@pwlazy this may be an issue of

**Comment by CoderHam** [comment] 2019-04-24 21:52
@pwlazy this issue may be caused because the docker is not run in **privileged** mode. Once you do this, it should allow **gdb** to function _normally_ inside the docker.
`docker run --privileged ..` 
More at: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by pwlazy** [comment] 2019-04-26 01:36
i have added “--privileged” before, but the error was the same

**Comment by GuanLuo** [comment] 2019-05-01 17:03
I am not sure what is the cause of this issue then. Do you mind to create a simple program and see if you can insert breakpoints into it? Just want to verify if it is due to the docker container or the build itself.

**Comment by pwlazy** [comment] 2019-05-05 01:44
two months before, on the same machine and environment, i tried to build the tensorrt inference client by Dockefile, then i started the image by adding   “--privileged” and enter the container to use gdb to debug the client , it worked

**Comment by deadeyegoodwin** [comment] 2019-06-06 16:31
Note that on master (and starting in release 19.07) we no longer use bazel to build and instead have a cmake-based build. Build instructions are here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/build.rst

The cmake build is more modular and should make it easier to build a debug version of TRTIS. Closing.

**Closed by deadeyegoodwin** 2019-06-06 16:31 UTC
